export const SPACE_IMAGES = {
  space1: (await import("./space1.jpg")).default,
  space2: (await import("./space2.jpg")).default,
  space3: (await import("./space3.jpg")).default,
  space4: (await import("./space4.jpg")).default,
  space5: (await import("./space5.jpg")).default,
  space6: (await import("./space6.jpg")).default,
  space7: (await import("./space7.jpg")).default,
  space8: (await import("./space8.jpg")).default,
  space9: (await import("./space9.jpg")).default,
  space10: (await import("./space10.jpg")).default,
  space11: (await import("./space11.jpg")).default,
  space12: (await import("./space12.jpg")).default,
  space13: (await import("./space13.jpg")).default,
  space14: (await import("./space14.jpg")).default,
  space15: (await import("./space15.jpg")).default,
  space16: (await import("./space16.jpg")).default,
  space17: (await import("./space17.jpg")).default,
  space18: (await import("./space18.jpg")).default,
  space19: (await import("./space19.jpg")).default,
  space20: (await import("./space20.jpg")).default,
  space21: (await import("./space21.jpg")).default,
  space22: (await import("./space22.jpg")).default,
};
